# Generated by Django 6.0.3 on 2026-03-12 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_item_buyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('books', 'Books'), ('electronics', 'Electronics'), ('fashion', 'Fashion'), ('furniture', 'Furniture'), ('bikes', 'Bikes'), ('gaming', 'Gaming'), ('phones', 'Phones'), ('laptops', 'Laptops'), ('sports', 'Sports'), ('appliances', 'Appliances'), ('other', 'Other')], max_length=50),
        ),
    ]
